kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: monitoramento
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3001  # Grafana
        hostPort: 3002
      - containerPort: 9090  # Prometheus
        hostPort: 9091
      - containerPort: 5000  # API Flask
        hostPort: 5001
