apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meu-projeto-api-monitoramento
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/seu-usuario/seu-repositorio.git' # <-- IMPORTANTE: Altere para a URL do seu repositório
    path: helm/meu-projeto-api-monitoramento
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoramento
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
